org.gradle.jvmargs=-Xmx4G

java_version=21

minecraft_version=1.21.5

group=net.wiredtomato
mod_id=template
mod_name=Template
mod_description=Template Description
mod_author=WiredTomato
mod_version=1.0.0

license=MIT

fabric_loader_version_override=
fabric_version_override=
flk_version_override=

neoforge_version_override=
kff_loader_version_range=[5,)
kff_version_override=
minecraft_version_range=[1.21,)
credits=

neo_form_version_override=
parchment_minecraft=1.21.4
parchment_version=2025.03.23

kotlin.code.style=official
